"use client";

import { useState } from "react";
import Image, { type StaticImageData } from "next/image";
import v1Image from "@/assets/recommendations/v1-ultra.jpg";
import k3Image from "@/assets/recommendations/k3-ultra.jpg";
import q11Image from "@/assets/recommendations/q11-ultra.jpg";
import { track } from "@/lib/analytics";
import type { LayoutName } from "@/lib/analytics-events";

type KeyboardRecommendation = {
  id: string;
  category: string;
  name: string;
  description: string;
  image: StaticImageData;
  imageAlt: string;
  affiliateUrl: string;
};

// Product links generated by the approved Keychron affiliate dashboard.
const keyboards: KeyboardRecommendation[] = [
  {
    id: "keychron-v1-ultra",
    category: "Everyday typing",
    name: "Keychron V1 Ultra 8K",
    description: "A compact wireless mechanical keyboard with a volume knob and hot-swappable switches. Customize the keys with Keychron Launcher.",
    image: v1Image,
    imageAlt: "Black Keychron V1 Ultra 8K keyboard with a volume knob and orange Escape key",
    affiliateUrl: "https://www.keychron.com/products/keychron-v1-ultra-8k-wireless-custom-mechanical-keyboard?ref=bcheofom",
  },
  {
    id: "keychron-k3-ultra",
    category: "Slim profile",
    name: "Keychron K3 Ultra 8K",
    description: "A slim wireless mechanical keyboard with low-profile keys for a shallower typing feel. Customize the keys with Keychron Launcher.",
    image: k3Image,
    imageAlt: "Black Keychron K3 Ultra 8K low-profile keyboard with wooden side panels",
    affiliateUrl: "https://www.keychron.com/products/keychron-k3-ultra-8k-wireless-custom-mechanical-keyboard?ref=bcheofom",
  },
  {
    id: "keychron-q11-ultra",
    category: "Split keyboard",
    name: "Keychron Q11 Ultra 8K",
    description: "An aluminum mechanical keyboard with two wireless halves you can position independently. Customize the keys with Keychron Launcher.",
    image: q11Image,
    imageAlt: "Black Keychron Q11 Ultra 8K split keyboard with two separate halves and teal accent keys",
    affiliateUrl: "https://www.keychron.com/products/keychron-q11-ultra-8k-wireless-custom-mechanical-keyboard?ref=bcheofom",
  },
];

export default function KeyboardRecommendations({ layout }: { layout: LayoutName }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <section aria-label="Keyboard recommendations">
      <button
        type="button"
        aria-expanded={isOpen}
        aria-controls="keyboard-recommendation-offers"
        onClick={() => {
          if (!isOpen) track("recommendations_opened", { layout, placement: "below_tester" });
          setIsOpen(!isOpen);
        }}
        className="inline-flex items-center gap-2 rounded-sm py-2 text-sm text-gray-500 hover:text-gray-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gray-500 dark:text-gray-400 dark:hover:text-gray-200"
      >
        Keyboard recommendations
        <svg
          aria-hidden="true"
          viewBox="0 0 16 16"
          fill="none"
          className={`h-3.5 w-3.5 ${isOpen ? "rotate-180" : ""}`}
        >
          <path d="m4 6 4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>

      <div id="keyboard-recommendation-offers" hidden={!isOpen} className="pt-5">
        <div className="grid gap-3 sm:grid-cols-3 sm:gap-4">
          {keyboards.map((keyboard) => (
            <a
              key={keyboard.id}
              href={keyboard.affiliateUrl}
              target="_blank"
              rel="sponsored noopener noreferrer"
              aria-label={`View ${keyboard.name} at Keychron (opens in a new tab)`}
              data-keyboard-recommendation={keyboard.id}
              onClick={() => track("affiliate_link_clicked", {
                layout, product_id: keyboard.id, merchant: "keychron", placement: "below_tester",
              })}
              onAuxClick={(event) => {
                if (event.button === 1) track("affiliate_link_clicked", {
                  layout, product_id: keyboard.id, merchant: "keychron", placement: "below_tester",
                });
              }}
              className="group flex flex-col rounded-xl border border-gray-200 p-4 transition-colors hover:border-gray-400 hover:bg-gray-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-amber-600 motion-reduce:transition-none dark:border-gray-800 dark:hover:border-gray-500 dark:hover:bg-gray-900/60"
            >
              <div className="mb-3 min-h-5 text-xs">
                <span className="text-gray-500 dark:text-gray-400">{keyboard.category}</span>
              </div>
              <div className="relative mb-4 aspect-[2.2/1] overflow-hidden rounded-md bg-white">
                <Image
                  src={keyboard.image}
                  alt={keyboard.imageAlt}
                  fill
                  sizes="(max-width: 639px) calc(100vw - 66px), (max-width: 1152px) 30vw, 310px"
                  className="scale-[1.12] object-cover object-[center_49%]"
                />
              </div>
              <h3 className="mb-2 text-base font-medium tracking-tight">{keyboard.name}</h3>
              <p className="mb-3 text-sm leading-relaxed text-gray-600 dark:text-gray-400">{keyboard.description}</p>
              <p className="mb-5 text-[11px] leading-relaxed text-gray-500 dark:text-gray-400">Fully assembled · QWERTY keycaps</p>
              <span className="mt-auto flex items-center justify-between border-t border-gray-200 pt-3 text-sm font-medium dark:border-gray-800">
                View at Keychron
              </span>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}
